SlnVideojuegos1/VideoJuegosSite/Controllers/JuegoGeneroController.cs
using Domain_Layer.Dtos;
using Domain_Layer.Queries;
using System.Collections.Generic;
using System.Web.Mvc;

namespace VideoJuegosSite.Controllers
{
    public class JuegoGeneroController : Controller
    {
        private IDJuegoGeneroQuery query;

        public ActionResult JuegoGeneroMain()
        {
            return View();
        }

        public ActionResult JuegoGeneroView()
        {
            return View();
        }

        public JsonResult ActualizarJuegoGenero(DJuegoGeneroDto dto)
        {
            query = new DQuerys();
            query.Update(dto);
            return null;
        }

        public JsonResult EliminarJuegoGenero(DJuegoGeneroDto dto)
        {
            query = new DQuerys();
            query.Delete(dto);
            return null;
        }

        public JsonResult InsertarJuegoGenero(DJuegoGeneroDto dto)
        {
            query = new DQuerys();
            query.Insert(dto);
            return null;
        }

        public JsonResult ListarJuegoGenero()
        {
            var list = new List<DJuegoGeneroDto>();
            query = new DQuerys();
            list = query.List(new DJuegoGeneroDto());
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

SlnVideojuegos1/VideoJuegosSite/Controllers/PackDetalleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VideoJuegosSite.Controllers
{
    public class PackDetalleController : Controller
    {
        public ActionResult PackDetalleMain()
        {
            return View();
        }

        public ActionResult PackDetalleView()
        {
            return View();
        }
    }
}

SlnVideojuegos1/VideoJuegosSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body ng-app="MyApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VideoJuegos", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Genero", "GeneroMain", "Genero")</li>
                    <li>@Html.ActionLink("Juego", "JuegoMain", "Juego")</li>
                    <li>@Html.ActionLink("Pack", "PackMain", "Pack")</li>
                    <li>@Html.ActionLink("Juego Genero", "JuegoGeneroMain", "JuegoGenero")</li>
                    <li>@Html.ActionLink("Pack Detalle", "PackDetalleMain", "PackDetalle")</li>
                    <li class="right">@Html.ActionLink("Login", "Login", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/Scripts")
    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>